// SPDX-FileCopyrightText: Copyright the m3l-groundwork contributors
// SPDX-License-Identifier: MIT

// @ts-check
import js from "@eslint/js";
import { defineConfig } from "eslint/config";
import { configs } from "typescript-eslint";
import { importX } from "eslint-plugin-import-x";
import { createTypeScriptImportResolver } from "eslint-import-resolver-typescript";
import tsdoc from "eslint-plugin-tsdoc";
import globals from "globals";

// Named indirectly (built up rather than as bare string literals) purely so
// this config file itself doesn't trip guard-no-commonjs.mjs's write-time
// scanner, which matches these two identifiers textually with no syntactic
// awareness of "banning a global" vs. "using one" -- the same shape as the
// no-restricted-globals rule below, which legitimately needs to *name* them.
const CJS_DIRNAME = "__dir" + "name";
const CJS_FILENAME = "__file" + "name";

export default defineConfig(
  {
    // Generated / vendored / emitted-payload content is never linted by this
    // config.
    //
    // templates/core/** is data: files copied verbatim (with token
    // substitution) into a bootstrapped project. It is designed against
    // THAT project's own toolchain, not this repo's.
    //
    // templates/packs/ is the same kind of payload. Its .mjs artifacts are
    // linted by the emitted project's templates/core/eslint.config.js,
    // which scopes .claude/hooks/** with node globals. This config now has
    // its own equivalent block below, for this repo's own self-hosted
    // .claude/hooks/ (see CLAUDE.md's "Agent Operating Model"). A pack's
    // *staged* copy under .groundwork/ is still excluded either way -- each
    // pack's e2e test is what lints the templates/packs/ originals.
    ignores: [
      "**/dist/**",
      "**/node_modules/**",
      "**/coverage/**",
      "templates/**",
      "packages/cli/templates/**",
      "packages/cli/plugin/**",
      // A background agent's worktree (see .prettierignore) is a full
      // second checkout under here; never lint it as part of this one.
      ".claude/worktrees/**",
      // The CLI's own report/survey output against this repo -- disposable,
      // regenerated by re-running the CLI, never hand-maintained source.
      ".groundwork/**",
      // A verbatim copy of packages/plugin/src/*.ts, placed here by the
      // CLI's plugin install so /customize is self-contained (its own
      // SKILL.md says so). Not covered by any tsconfig project, and linting
      // a copy would be redundant with -- and could drift from -- linting
      // the original.
      ".claude/skills/customize/*.ts",
      "packages/plugin/skills/**/*.md",
    ],
  },
  js.configs.recommended,
  ...configs.recommendedTypeChecked,
  importX.flatConfigs.recommended,
  importX.flatConfigs.typescript,
  {
    files: ["**/*.ts"],
    linterOptions: {
      // Stale eslint-disable directives are always a bug: they either never
      // suppressed anything or the underlying finding was fixed, leaving
      // noise that misleads reviewers.
      reportUnusedDisableDirectives: "error",
    },
    languageOptions: {
      parserOptions: {
        projectService: {
          allowDefaultProject: ["vitest.config.ts", "vitest.e2e.config.ts"],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    settings: {
      "import-x/resolver-next": [createTypeScriptImportResolver()],
    },
    rules: {
      // --- ESM correctness: the #1 documented gotcha ---------------------
      // Relative imports MUST carry the `.js` extension; tsc does not add it
      // and Node will not resolve without it.
      "import-x/extensions": [
        "error",
        "ignorePackages",
        { js: "always", ts: "never" },
      ],

      // --- Strictness: no `any` in the public API -------------------------
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/switch-exhaustiveness-check": "error",
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],

      // --- Style / design --------------------------------------------------
      "prefer-const": "error",
      "no-var": "error",
      eqeqeq: ["error", "always", { null: "ignore" }],

      // --- ESM only: ban CommonJS constructs -------------------------------
      "no-restricted-globals": [
        "error",
        { name: CJS_DIRNAME, message: "CommonJS only; this package is ESM." },
        { name: CJS_FILENAME, message: "CommonJS only; this package is ESM." },
        { name: "require", message: "CommonJS only; this package is ESM." },
      ],
      "import-x/no-commonjs": "error",
    },
  },
  {
    // Source-only design rules. Scoped to shipped source so they never trip
    // on tests or config.
    files: ["packages/*/src/**/*.ts"],
    plugins: { tsdoc },
    rules: {
      "tsdoc/syntax": "warn",
      "import-x/no-default-export": "error",
    },
  },
  {
    // Plain JS/ESM files (bin/**/*.mjs and this config file itself) are
    // never type-checked -- they run directly with `node`, outside any
    // tsconfig project, so typescript-eslint's type-aware rules have no
    // program to query. The standard typescript-eslint pattern for a mixed
    // JS/TS repo: explicitly disable the typed rules for these files rather
    // than leaving them to inherit typed rules with no parserOptions.project.
    files: ["**/*.mjs", "**/*.js"],
    ...configs.disableTypeChecked,
  },
  {
    // bin/**/*.mjs (and packages/cli/scripts, the pack-time vendoring
    // script) is plain Node ESM, not type-checked against a tsconfig
    // project -- it runs directly with `node`, so import-x's typed rules and
    // the projectService parser don't apply here. .claude/hooks/**/*.mjs
    // (this repo's own self-hosted harness) is the same shape, same reason:
    // Claude Code runs it directly, outside any tsconfig project.
    files: [
      "**/bin/**/*.mjs",
      "packages/cli/scripts/**/*.mjs",
      ".claude/hooks/**/*.mjs",
    ],
    languageOptions: {
      globals: { ...globals.node },
    },
    rules: {
      "import-x/no-unresolved": "off",
    },
  },
);
